### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by ateska** [hypersoft/nargv#1]
Hi,

Excellent piece of code!
It would be awesome if you attach some kind of license to that.
I could boost adoption of that in other projects significantly.

Best regards,
Ales Teska

**Comment by hypersoft** [comment]
Uh, well, add any license you want to your project. That is the point. Voids are made to be filled.

**Comment by hypersoft** [comment]
Officially, this is just example code of how to parse a shell string in C. One would expect to see something like this in a book, or on a website. Royalty free, because, no claims were made.

Despite what most have been taught, if nothing was said about a thing, then nothing is reserved. Furthermore, nobody can blame you for anything they do with your code. That's like trying to sue a firearms manufacturer for selling guns.

**Comment by hypersoft** [comment]
I would counter sue for the frivolity.

**Comment by hypersoft** [comment]
Where the situation gets hairy, is when you make claims asserting this or that being feasible to perform a particular task, and you charge a fee for the licensing, without a "disclaimer". Its called warranty spoilation when things don't perform as you said, and you took the money for the software in an exchange.

**Comment by hypersoft** [comment]
[Nothing ventured, nothing gained: liability]

**Comment by hypersoft** [comment]
Wrapping this up for good: Whatever license you want, with no liabities on my behalf, because you have not given me any thing in exchange for a product.
